// DRAFT legal templates — review with a professional before launch. These are
// reasonable starting points for a small SaaS, not legal advice.

const UPDATED = 'July 2026'

function Shell({ title, onBack, children }) {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100">
      <div className="max-w-2xl mx-auto px-5 sm:px-8 py-10">
        <button
          onClick={onBack}
          className="text-sm text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 mb-6"
        >
          ← Back
        </button>
        <h1 className="text-2xl font-bold mb-1">{title}</h1>
        <p className="text-xs text-slate-500 mb-8">Last updated: {UPDATED}</p>
        <div className="space-y-5 text-sm text-slate-600 dark:text-slate-300 leading-relaxed [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-slate-900 [&_h2]:dark:text-slate-100 [&_h2]:mt-6">
          {children}
        </div>
      </div>
    </div>
  )
}

export function Terms({ onBack }) {
  return (
    <Shell title="Terms of Service" onBack={onBack}>
      <p>
        By creating an account or using DocChat (“the Service”), you agree to these
        terms. If you don’t agree, please don’t use the Service.
      </p>
      <h2>Your account</h2>
      <p>
        You’re responsible for keeping your login secure and for activity under your
        account. You must be old enough to form a binding contract in your country.
      </p>
      <h2>Acceptable use</h2>
      <p>
        Upload only documents you have the right to use. Don’t use the Service to
        break the law, infringe others’ rights, or attempt to disrupt or reverse-engineer it.
        We may suspend accounts that abuse the Service or its usage limits.
      </p>
      <h2>Your content</h2>
      <p>
        You keep all rights to the documents you upload. You grant us a limited right
        to process them solely to provide the Service (parsing, indexing, and answering
        your questions). We don’t sell your content or use it to train models.
      </p>
      <h2>AI answers</h2>
      <p>
        Answers are generated by an AI model from your documents and may be incomplete
        or wrong. Always verify important information against the cited source. The
        Service is provided “as is,” without warranties.
      </p>
      <h2>Limitation of liability</h2>
      <p>
        To the extent permitted by law, DocChat is not liable for indirect or
        consequential damages, or for decisions made based on AI-generated answers.
      </p>
      <h2>Changes & termination</h2>
      <p>
        We may update these terms or the Service over time. You can delete your account
        at any time from the app. We may terminate accounts that violate these terms.
      </p>
      <h2>Contact</h2>
      <p>Questions? Reach us at the email address on our website.</p>
    </Shell>
  )
}

export function Privacy({ onBack }) {
  return (
    <Shell title="Privacy Policy" onBack={onBack}>
      <p>
        This policy explains what DocChat collects, why, and the control you have over
        your data.
      </p>
      <h2>What we collect</h2>
      <p>
        <strong>Account data:</strong> your email address, handled by our
        authentication provider (Supabase). <strong>Your documents:</strong> the PDFs
        you upload and the text extracted from them. <strong>Chat history:</strong>
        your questions and the AI’s answers. <strong>Basic usage metrics:</strong>
        privacy-respecting, cookieless analytics (page views and signups) — no
        cross-site tracking.
      </p>
      <h2>How we use it</h2>
      <p>
        Solely to run the Service: to authenticate you, index your documents, answer
        your questions, and enforce fair-use limits. Your documents and questions are
        sent to our AI provider (Google Gemini) only to generate answers. We do not
        sell your data or use your content to train AI models.
      </p>
      <h2>Storage & security</h2>
      <p>
        Data is stored on managed infrastructure with encryption in transit. Every
        query is strictly scoped to your account — other users can never access your
        documents or chats.
      </p>
      <h2>Your rights & control</h2>
      <p>
        You can delete individual documents at any time. You can also permanently
        delete <em>all</em> your data and your account from Settings in the app — this
        removes your uploaded files, the search index, your conversations, and your
        account. Deletion is immediate and irreversible.
      </p>
      <h2>Data retention</h2>
      <p>
        We keep your data until you delete it or close your account. Backups may
        persist for a short period after deletion before being overwritten.
      </p>
      <h2>Contact</h2>
      <p>For any privacy request, contact us at the email address on our website.</p>
    </Shell>
  )
}
